name: Deploy
description: Deploy the microsite

inputs:
  folder_name:
    description: The folder under sites.eventray.com
    required: true

  build_path:
    description: The local folder containing the content to push
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.folder_name}}
    - ${{ inputs.build_path }}
